<?php

/**
 * @file
 * The OpenEuropa Contact Forms installation file.
 */

declare(strict_types = 1);

/**
 * Implements hook_install().
 */
function oe_contact_forms_install() {
  // Configure the RDF SKOS graphs.
  if (!\Drupal::service('config.installer')->isSyncing()) {
    $graphs = [
      'country' => 'http://publications.europa.eu/resource/authority/country',
    ];
    \Drupal::service('rdf_skos.skos_graph_configurator')->addGraphs($graphs);
  }
}
