contact.form.*.third_party.oe_contact_forms:
  type: mapping
  label: 'Contact form corporate fields'
  mapping:
    is_corporate_form:
      type: boolean
      label: 'Is corporate form'
    topic_name:
      type: sequence
      label: 'Topic name'
      sequence:
        type: string
    topic_label:
      type: string
      label: 'Topic label'
