# Schema for the configuration files of the OE Contact Forms module.

contact.form.*.third_party.oe_contact_forms:
  type: mapping
  label: 'OE Contact Forms settings'
  mapping:
    is_corporate_form:
      type: boolean
      label: 'Is corporate form'
    topic_label:
      type: label
      label: 'Topic label'
    email_subject:
      type: label
      label: 'Email subject'
    header:
      type: text
      label: 'Header'
    privacy_policy:
      type: text
      label: 'Privacy policy'
    includes_fields_in_auto_reply:
      type: boolean
      label: 'Includes fields in auto-reply'
    allow_canonical_url:
      type: boolean
      label: 'Allow canonical URL'
    expose_as_block:
      type: boolean
      label: 'Expose as block'
    optional_fields:
      type: mapping
      label: 'Optional fields'
      mapping:
        oe_country_residence:
          type: string
          label: 'Country of residence'
        oe_preferred_language:
          type: string
          label: 'Preferred contact language'
        oe_alternative_language:
          type: string
          label: 'Alternative contact language'
        oe_telephone:
          type: string
          label: 'Phone'
    override_languages:
      type: mapping
      label: 'Override languages'
      mapping:
        oe_preferred_language_options:
          type: sequence
          label: 'Preferred contact language options'
          sequence:
            type: string
            label: 'Skos term'
        oe_alternative_language_options:
          type: sequence
          label: 'Alternative contact language options'
          sequence:
            type: string
            label: 'Skos term'
    topics:
      type: sequence
      sequence:
        type: mapping
        mapping:
          topic_name:
            type: label
            label: 'Topic name'
          topic_email_address:
            type: email
            label: 'Topic email address(es)'
    alternative_name:
      type: boolean
      label: 'Use First name and Last name for the form'
