<?php

/**
 * @file
 * Honeypot for Contact Forms module.
 */

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Add Honeypot features to all contact message forms.
 */
function oe_contact_forms_honeypot_form_contact_message_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('honeypot')->addFormProtection($form, $form_state, [
    'honeypot',
    'time_restriction',
  ]);
}
